name: capital_quiz
description: Capital Quiz

dependencies:
  flutter:
    sdk: flutter
  english_words: ^3.1.0
  random_color: ^1.0.3


  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/flags/
    - assets/mainJson.json

  fonts:
    - family: Kranky
      fonts:
        - asset: assets/fonts/Kranky-Regular.ttf
          weight: 400